---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 13.6.4

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-9.4
  - name: debian-8.10
  - name: centos-7.4
  - name: centos-6.9
  - name: fedora-27
  - name: freebsd-11.1
  - name: freebsd-10.4
  - name: mwrock/Windows2016
    transport:
      name: winrm
  - name: mwrock/Windows2012R2
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[chef_run_recorder::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
