---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 13.6.4

verifier:
  name: inspec

# Every bento box supported by Chef 13
platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-16.04-i386
  - name: ubuntu-14.04
  - name: ubuntu-14.04-i386
  - name: ubuntu-12.04 # Chef 13 dropped support
  - name: ubuntu-12.04-i386 # Chef 13 dropped support
  - name: debian-9.4
  - name: debian-9.4-i386
  - name: debian-8.10
  - name: debian-8.10-i386
  - name: debian-7.11 # Ruby requires GLIBC
  - name: debian-7.11-i386 # Ruby requires GLIBC
  - name: centos-7.4
  - name: centos-6.9
  - name: centos-6.9-i386
  - name: centos-5.11
  - name: centos-5.11-i386
  - name: oracle-7.4
  - name: oracle-6.9
  - name: oracle-6.9-i386
  - name: oracle-5.11
  - name: oracle-5.11-i386
  - name: fedora-27
  - name: fedora-26
  - name: opensuse-leap-42.3
  - name: freebsd-11.1
  - name: freebsd-11.1-i386 # Chef install fails
  - name: freebsd-10.4
  - name: freebsd-10.4-i386 # Box does not exist
  - name: mwrock/Windows2016
    transport:
      name: winrm
  - name: mwrock/Windows2012R2
    transport:
      name: winrm
  - name: opentable/win-2008r2-standard-amd64-nocm
    transport:
      name: winrm

suites:
  - name: debian-based
    run_list:
      - recipe[chef_run_recorder::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    includes:
      - ubuntu-18.04
      - ubuntu-16.04
      - ubuntu-16.04-i386
      - ubuntu-14.04
      - ubuntu-14.04-i386
      - debian-9.4
      - debian-9.4-i386
      - debian-8.10
      - debian-8.10-i386
  - name: rhel-based
    run_list:
      - recipe[chef_run_recorder::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    includes:
      - centos-7.4
      - centos-6.9
      - centos-6.9-i386
      - centos-5.11
      - centos-5.11-i386
      - oracle-7.4
      - oracle-6.9
      - oracle-6.9-i386
      - oracle-5.11
      - oracle-5.11-i386
      - fedora-27
      - fedora-26
  - name: all-others
    run_list:
      - recipe[chef_run_recorder::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    includes:
      - opensuse-leap-42.3
      - freebsd-11.1
      - freebsd-10.4
      - mwrock/Windows2016
      - mwrock/Windows2012R2
      - opentable/win-2008r2-standard-amd64-nocm
